### PR TITLE
milestone5: make the webpage accessible

### PR DESCRIPTION
**Pull request by GedeonTS**
# PORTFOLIO

## milestone5:make the webpage accessible

in this part we made accessibility checks using the following:
- **page title:** changed the page [title](https://github.com/GedeonTS/PORTFOLIO/blob/00836d06bd211949fe8ea1fa9e6a40c6f4c4ef04/index.html#L18)
- **"Alt" image attributes:** Changed all the [alt](https://github.com/GedeonTS/PORTFOLIO/blob/00836d06bd211949fe8ea1fa9e6a40c6f4c4ef04/index.html#L47) attributes to describe the images.
- **Headings:** No issues were found.
- **Color contrast:** no issue found. 
- **Resize:** no issues were found.
- **Interactions:** no issues were found.
- **Moving content:** no issues were found.
- **Multimedia:** no issues were found.
- **Basic structure of the page:** no issues were found.

### CODE REVIEW

**Review by omar-muhamad — CHANGES_REQUESTED** [review]
# Changes Required ♻️
### Hi @GedeonTS,

Nice job, you are almost there.



## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [x] You have a contrast ratio issue on your form submission button with all stats normal, hover, and active Please fix that.

image

and you can test it after you do the changes [here](https://www.aditus.io/button-contrast-checker/).

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by GedeonTS** [comment]
Hello! @Omar-Muhamad, we have made some changes but we couldn't be able to display for test using the link and see them. how do we proceed?

**Comment by omar-muhamad** [comment]
> Hello! @Omar-Muhamad, we have made some changes but we couldn't be able to display for test using the link and see them. how do we proceed?

Use your deployment link in the site i gave you and the test will work.

**Comment by Kwentsir** [comment]
> > Hello! @Omar-Muhamad, we have made some changes but we couldn't be able to display for test using the link and see them. how do we proceed?
> 
> Use your deployment link in the site i gave you and the test will work.

@Omar-Muhamad, we have updated our accessibility branch. The issue we have now is, we don't see the changes we implemented on the website so if we test it, we still get the results generated in the pull requested that you reviewed. How will our changes be reflected on the website for us to perform the test again?

**Review by ShadyShawkat — APPROVED** [review]
## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
